@echo off
echo Cleaning old class files...
del /s /q *.class >nul 2>&1
echo Compiling...
javac -d build -cp "lib/*" src/main/Main.java src/api/*.java src/report/*.java src/service/*.java src/database/*.java

echo Starting React Frontend Server (Vite)...
start "MLD React Frontend" cmd /c "cd frontend && npm run dev"

echo Starting Backend API Server on Port 3000...
java -cp "lib/*;build" main.Main
pause
