@echo off
echo Cleaning old class files...
del /s /q *.class >nul 2>&1
echo Compiling...
javac -cp "lib/*;src" src/main/Main.java src/api/*.java src/monitor/*.java src/report/*.java src/service/*.java src/agent/*.java
echo Starting Backend Server...
java -cp "lib/*;src" main.Main
pause
