@echo off
echo Cleaning old class files...
del /s /q *.class >nul 2>&1
echo Compiling...
javac -d build -cp "lib/*" src/main/Main.java src/api/*.java src/monitor/*.java src/report/*.java src/service/*.java src/agent/*.java src/database/*.java

echo Starting Frontend UI Server on Port 8080...
start "MLD Frontend Server" cmd /c "npx -y http-server -p 8080 -c-1"

echo Starting Backend API Server on Port 3000...
java -cp "lib/*;build" main.Main
pause
