using System;
using System.IO;
using System.Text;

namespace MldAgent.Configuration
{
    public class AgentConfiguration
    {
        private static readonly string ConfigFilePath = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
            ".mld_agent.properties"
        );

        public string ServerUrl { get; set; }
        public string Uuid { get; set; }
        public string Email { get; set; }
        public string EmployeeName { get; set; }
        public int TelemetryIntervalSeconds { get; set; }
        public int HeartbeatIntervalSeconds { get; set; }

        public AgentConfiguration()
        {
            ServerUrl = "https://mld-server.onrender.com";
            Uuid = "";
            Email = "";
            EmployeeName = "Employee";
            TelemetryIntervalSeconds = 10;
            HeartbeatIntervalSeconds = 30;
        }

        public static AgentConfiguration Load()
        {
            var config = new AgentConfiguration();
            if (!File.Exists(ConfigFilePath))
            {
                return config;
            }

            try
            {
                string[] lines = File.ReadAllLines(ConfigFilePath, Encoding.UTF8);
                foreach (string line in lines)
                {
                    string trimmed = line.Trim();
                    if (string.IsNullOrEmpty(trimmed) || trimmed.StartsWith("#") || trimmed.StartsWith("!"))
                        continue;

                    int splitIndex = trimmed.IndexOf('=');
                    if (splitIndex <= 0) continue;

                    string key = trimmed.Substring(0, splitIndex).Trim();
                    string val = trimmed.Substring(splitIndex + 1).Trim().Replace("\\:", ":").Replace("\\=", "=").Replace("\\/", "/");

                    switch (key.ToLowerInvariant())
                    {
                        case "serverurl":
                            if (!string.IsNullOrEmpty(val))
                            {
                                val = val.Replace("\\:", ":").Replace("\\/", "/").Trim();
                                if (!val.StartsWith("http://", StringComparison.OrdinalIgnoreCase) && !val.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
                                {
                                    val = "https://mld-server.onrender.com";
                                }
                                config.ServerUrl = val;
                            }
                            break;
                        case "uuid":
                            config.Uuid = val;
                            break;
                        case "email":
                            config.Email = val;
                            break;
                        case "employeename":
                            if (!string.IsNullOrEmpty(val)) config.EmployeeName = val;
                            break;
                    }
                }
            }
            catch (Exception ex)
            {
                Logging.AgentLogger.LogError("Failed to load configuration", ex);
            }

            Logging.AgentLogger.LogInfo(string.Format("Config loaded: ServerUrl={0}, Uuid={1}", config.ServerUrl, config.Uuid));
            return config;
        }

        public void Save()
        {
            try
            {
                var sb = new StringBuilder();
                sb.AppendLine("# MLD Desktop Workstation Agent Configuration");
                sb.AppendLine("# Automatically generated by MLD-Agent native client");
                sb.AppendLine(string.Format("serverUrl={0}", ServerUrl));
                sb.AppendLine(string.Format("uuid={0}", Uuid));
                sb.AppendLine(string.Format("email={0}", Email));
                sb.AppendLine(string.Format("employeeName={0}", EmployeeName));

                File.WriteAllText(ConfigFilePath, sb.ToString(), Encoding.UTF8);
                Logging.AgentLogger.LogInfo("Configuration saved successfully.");
            }
            catch (Exception ex)
            {
                Logging.AgentLogger.LogError("Failed to save configuration", ex);
            }
        }

        public void UpdateToken(string newUuid)
        {
            if (string.IsNullOrEmpty(newUuid)) return;
            newUuid = newUuid.Trim();
            if (newUuid.EndsWith("/")) newUuid = newUuid.TrimEnd('/');
            Uuid = newUuid;
            Save();
        }
    }
}
